name: BUILD

on:
  watch:
      types: [started]

jobs:
  debug:
    runs-on: macos-latest
    steps:
     - name: SSH 连接到 Actions
       uses: P3TERX/ssh2actions@main
       env:
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}    
